@extends('layouts.app')
@section('title', 'Dashboard · Ruang Baca')
@section('eyebrow', 'Dashboard')
@section('content')
<section class="dashboard page">
    <div class="hero-card">
        <div><p class="eyebrow">Ruang kerja Anda</p><h1>Selamat datang, {{ Auth::user()->name }}.</h1><p>Seluruh koleksi dan komunitas perpustakaan, dalam satu tempat yang tenang dan terorganisir.</p><div class="hero-card__actions"><a class="btn btn--light" href="{{ route('books.create') }}">Tambah buku</a><a class="text-link" href="{{ route('books.index') }}">Lihat koleksi <span>→</span></a></div></div>
        <div class="hero-card__ornament" aria-hidden="true"><span>✦</span><i></i><b></b></div>
    </div>
    <div class="section-heading"><div><p class="eyebrow">Ringkasan</p><h2>Gambaran perpustakaan</h2></div><span class="section-heading__note">Data diperbarui saat ini</span></div>
    <div class="stats-grid">
        <a class="stat-card" href="{{ route('books.index') }}"><span class="stat-card__icon icon--teal">▤</span><span><small>Total koleksi</small><strong>{{ number_format($totalBooks, 0, ',', '.') }}</strong><em>Judul buku terdaftar</em></span><b aria-hidden="true">→</b></a>
        <a class="stat-card" href="{{ route('members.index') }}"><span class="stat-card__icon icon--gold">♙</span><span><small>Anggota aktif</small><strong>{{ number_format($totalMembers, 0, ',', '.') }}</strong><em>Terdaftar di perpustakaan</em></span><b aria-hidden="true">→</b></a>
        <a class="stat-card" href="{{ route('categories.index') }}"><span class="stat-card__icon icon--blue">◇</span><span><small>Kategori</small><strong>{{ number_format($totalCategories, 0, ',', '.') }}</strong><em>Pengelompokan koleksi</em></span><b aria-hidden="true">→</b></a>
        @if (Auth::user()->role === 'admin')<a class="stat-card" href="{{ route('users.index') }}"><span class="stat-card__icon icon--rose">◉</span><span><small>Pengguna sistem</small><strong>{{ number_format($totalUsers, 0, ',', '.') }}</strong><em>Admin & staf</em></span><b aria-hidden="true">→</b></a>@endif
    </div>
    <div class="dashboard__lower"><section class="action-panel"><p class="eyebrow">Aksi cepat</p><h2>Mulai pekerjaan Anda</h2><div class="quick-actions"><a href="{{ route('books.create') }}"><span>+</span><strong>Tambah buku</strong><small>Catat koleksi baru</small></a><a href="{{ route('members.create') }}"><span>+</span><strong>Tambah anggota</strong><small>Daftarkan pembaca</small></a><a href="{{ route('categories.create') }}"><span>+</span><strong>Tambah kategori</strong><small>Rapikan koleksi</small></a></div></section><aside class="tip-card"><span class="tip-card__icon">✦</span><p class="eyebrow">Tips pengelolaan</p><h3>Koleksi rapi, pencarian lebih cepat.</h3><p>Gunakan kategori yang konsisten agar setiap buku mudah ditemukan.</p><a href="{{ route('categories.index') }}">Kelola kategori →</a></aside></div>
    <section class="task-center" aria-labelledby="taskCenterTitle">
        <div class="section-heading"><div><p class="eyebrow">Pusat tindakan</p><h2 id="taskCenterTitle">Yang perlu diperiksa</h2></div><a class="text-action" href="{{ route('warnings.index', ['open' => 1]) }}">Buka peringatan →</a></div>
        <p class="task-center__intro">Mulai dari sini agar tugas petugas tidak terlewat. Angka berubah otomatis mengikuti aktivitas siswa.</p>
        <div class="task-center__grid">
            @foreach($actionItems as $item)
                <a class="task-item {{ $item['count'] ? 'task-item--active' : '' }}" href="{{ $item['url'] }}" aria-label="{{ $item['label'] }}: {{ $item['count'] }} item. {{ $item['description'] }}">
                    <strong class="task-item__icon" aria-hidden="true">{{ $item['icon'] }}</strong>
                    <span><b>{{ $item['label'] }}</b><small>{{ $item['description'] }}</small></span>
                    <i class="task-item__count">{{ $item['count'] }}</i>
                    <em aria-hidden="true">→</em>
                </a>
            @endforeach
        </div>
    </section>
    <div class="section-heading"><div><p class="eyebrow">Sirkulasi</p><h2>Kondisi transaksi</h2></div><a class="text-action" href="{{ route('borrowings.index') }}">Lihat semua transaksi →</a></div>
    <div class="transaction-stats"><article><small>Sedang dipinjam</small><strong>{{ number_format($activeBorrowings,0,',','.') }}</strong><span>Transaksi aktif</span></article><article><small>Terlambat</small><strong>{{ number_format($overdueBorrowings,0,',','.') }}</strong><span>Perlu ditindaklanjuti</span></article><article><small>Sudah kembali</small><strong>{{ number_format($returnedBorrowings,0,',','.') }}</strong><span>Riwayat pengembalian</span></article><article><small>Total denda</small><strong>Rp{{ number_format($totalFines,0,',','.') }}</strong><span>Dari transaksi selesai</span></article></div>
    <section class="recent-panel"><div class="recent-panel__heading"><div><p class="eyebrow">Aktivitas terbaru</p><h2>Transaksi terkini</h2></div><a class="btn btn--secondary" href="{{ route('borrowings.create') }}">+ Catat peminjaman</a></div>@forelse($recentBorrowings as $borrowing)<a class="activity-row" href="{{ route('borrowings.show',$borrowing) }}"><span class="activity-row__icon {{ $borrowing->status === 'returned' ? 'activity-row__icon--returned' : '' }}">{{ $borrowing->status === 'returned' ? '↓' : '↑' }}</span><span><strong>{{ $borrowing->member->name }} {{ $borrowing->status === 'returned' ? 'mengembalikan' : 'meminjam' }} {{ $borrowing->book->title }}</strong><small>{{ $borrowing->created_at->diffForHumans() }}</small></span><span class="activity-row__status">{{ $borrowing->status === 'returned' ? 'Dikembalikan' : ($borrowing->is_overdue ? 'Terlambat' : 'Dipinjam') }}</span></a>@empty<div class="empty-state empty-state--small"><span>↺</span><h2>Belum ada aktivitas transaksi</h2><p>Mulai dengan mencatat peminjaman pertama.</p></div>@endforelse</section>
    <div class="insight-grid"><section class="insight-card"><p class="eyebrow">{{ $circulationPeriodLabel }}</p><h2>Tren sirkulasi</h2>@if($weeklyStats->isNotEmpty())<div class="mini-chart" role="img" aria-label="Grafik peminjaman dan pengembalian {{ strtolower($circulationPeriodLabel) }}">@foreach($weeklyStats as $day)<div class="mini-chart__day"><div class="mini-chart__bars"><i title="Dipinjam: {{ $day['borrowed'] }}" style="height: {{ $day['borrowed'] ? max(8, round(($day['borrowed'] / $circulationChartMaximum) * 100)) : 3 }}%"></i><b title="Dikembalikan: {{ $day['returned'] }}" style="height: {{ $day['returned'] ? max(8, round(($day['returned'] / $circulationChartMaximum) * 100)) : 3 }}%"></b></div><small>{{ $day['label'] }}</small></div>@endforeach</div><div class="chart-legend"><span><i></i> Dipinjam</span><span><b></b> Dikembalikan</span></div>@else<div class="chart-empty-state"><span aria-hidden="true">↺</span><p>Belum ada transaksi. Grafik akan mulai terisi setelah peminjaman pertama dicatat.</p></div>@endif</section><section class="insight-card"><p class="eyebrow">Peringkat transaksi</p><h2>Terpopuler & teraktif</h2><div class="rank-columns"><div><h3>Buku terpopuler</h3>@forelse($popularBooks as $index => $item)<p><span>{{ $index+1 }}</span><strong>{{ $item->book->title }}</strong><small>{{ $item->transaction_count }}×</small></p>@empty<p class="rank-empty">Belum ada data.</p>@endforelse</div><div><h3>Anggota teraktif</h3>@forelse($activeMembers as $index => $item)<p><span>{{ $index+1 }}</span><strong>{{ $item->member->name }}</strong><small>{{ $item->transaction_count }}×</small></p>@empty<p class="rank-empty">Belum ada data.</p>@endforelse</div></div></section></div>
</section>
@endsection
