@extends('layouts.app')
@section('title', 'Koleksi Buku · Ruang Baca')
@section('eyebrow', 'Koleksi buku')
@section('content')
<section class="page">
    <div class="page-header"><div><p class="eyebrow">Manajemen koleksi</p><h1>Daftar buku</h1><p>Temukan, tinjau, dan perbarui seluruh koleksi perpustakaan.</p></div><div class="page-header__actions"><div class="view-toggle" id="viewToggle" aria-label="Pilih tampilan"><button type="button" class="view-toggle__btn view-toggle__btn--active" data-view="table" aria-label="Tampilan tabel">☷</button><button type="button" class="view-toggle__btn" data-view="catalog" aria-label="Tampilan katalog">▦</button></div><a href="{{ route('books.create') }}" class="btn btn--primary">+ Tambah buku</a></div></div>
    <form method="GET" action="{{ route('books.index') }}" class="filter-bar"><div class="search-field"><label class="sr-only" for="bookSearch">Cari koleksi</label><span>⌕</span><input id="bookSearch" type="search" name="search" placeholder="Cari judul atau penulis…" value="{{ $search }}"></div><div class="filter-bar__controls"><select name="category" aria-label="Filter kategori"><option value="">Semua kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected($categoryId == $category->id)>{{ $category->name }}</option>@endforeach</select><select name="status" aria-label="Filter ketersediaan"><option value="">Semua status</option><option value="tersedia" @selected($status === 'tersedia')>Tersedia</option><option value="habis" @selected($status === 'habis')>Stok habis</option></select><button class="btn btn--secondary" type="submit">Terapkan</button>@if ($search || $categoryId || $status)<a class="filter-reset" href="{{ route('books.index') }}">Reset</a>@endif</div></form>
    <div class="table-card page-view" id="tableView"><div class="table-card__meta"><span>{{ $books->count() }} buku ditemukan</span><span>Stok diperbarui dari data koleksi</span></div><div class="table-wrapper"><table class="data-table"><thead><tr><th scope="col">Buku</th><th scope="col">Kategori</th><th scope="col">Stok</th><th scope="col">Status</th><th scope="col"><span class="sr-only">Aksi</span></th></tr></thead><tbody>@forelse ($books as $book)<tr><td><div class="book-cell">@if ($book->cover_image)<img src="{{ asset('storage/' . $book->cover_image) }}" alt="Cover {{ $book->title }}">@else<div class="book-cover-placeholder" aria-hidden="true">B</div>@endif<div><a class="book-cell__title" href="{{ route('books.show', $book) }}">{{ $book->title }}</a><small>{{ $book->author }}@if($book->publication_year) · {{ $book->publication_year }}@endif</small></div></div></td><td>{{ $book->category->name }}</td><td><strong>{{ $book->stock }}</strong> eksemplar</td><td><span class="badge {{ $book->stock > 0 ? 'badge--success' : 'badge--danger' }}">{{ $book->stock > 0 ? 'Tersedia' : 'Stok habis' }}</span></td><td><div class="table-actions"><a href="{{ route('books.show', $book) }}" class="icon-button" title="Lihat detail" aria-label="Lihat detail {{ $book->title }}">↗</a><a href="{{ route('books.edit', $book) }}" class="icon-button" title="Edit" aria-label="Edit {{ $book->title }}">✎</a><form method="POST" action="{{ route('books.destroy', $book) }}" class="inline-form js-confirm-delete" data-name="{{ $book->title }}">@csrf @method('DELETE')<button type="submit" class="icon-button icon-button--danger" title="Hapus" aria-label="Hapus {{ $book->title }}">×</button></form></div></td></tr>@empty<tr><td colspan="5"><div class="empty-state"><span>▤</span><h2>Belum ada buku yang ditampilkan</h2><p>Tambahkan buku pertama atau sesuaikan pencarian dan filter Anda.</p><a href="{{ route('books.create') }}" class="btn btn--primary">+ Tambah buku</a></div></td></tr>@endforelse</tbody></table></div></div>
    <div class="page-view" id="catalogView" hidden><div class="book-catalog" id="bookCatalogGrid"></div></div><script>window.realBookCatalogData = @json($booksForCatalog);</script>
</section>
@endsection
