@extends('layouts.app')
@section('title', 'Eksemplar Buku · Ruang Baca')
@section('eyebrow', 'Inventaris')
@section('content')
<section class="page"><div class="page-header"><div><p class="eyebrow">Inventaris fisik</p><h1>Eksemplar & barcode</h1><p>Catat setiap salinan buku agar pelacakan rak, kondisi, dan barcode lebih rapi.</p></div></div>
@php($statusLabels = ['available' => 'Tersedia', 'borrowed' => 'Dipinjam', 'maintenance' => 'Perbaikan', 'lost' => 'Hilang'])
<div class="form-card form-card--compact inventory-create"><div class="form-card__header"><h2>Tambah eksemplar</h2><p>Kode inventaris wajib unik. Barcode dapat dipindai dengan scanner USB di kolom ini.</p></div><form method="POST" action="{{ route('book-copies.store') }}">@csrf<div class="form-grid"><div class="form-group form-group--wide"><label for="book_id">Judul buku</label><select id="book_id" name="book_id" required><option value="">Pilih buku</option>@foreach($books as $book)<option value="{{ $book->id }}">{{ $book->title }}{{ $book->book_code ? ' · '.$book->book_code : '' }}</option>@endforeach</select></div><div class="form-group"><label for="inventory_code">Kode inventaris</label><input id="inventory_code" name="inventory_code" placeholder="INV-2026-001" required></div><div class="form-group"><label for="barcode">Barcode</label><input id="barcode" name="barcode" placeholder="Opsional"></div><div class="form-group"><label for="condition">Kondisi</label><select id="condition" name="condition"><option value="good">Baik</option><option value="minor_damage">Rusak ringan</option><option value="damaged">Rusak</option></select></div></div><div class="form-actions"><button type="submit" class="btn btn--primary">Simpan eksemplar</button></div></form></div>
<form class="filter-bar inventory-filter" method="GET" action="{{ route('book-copies.index') }}"><div class="search-field"><label class="sr-only" for="copySearch">Cari eksemplar</label><span aria-hidden="true" data-solar-icon="solar:magnifer-linear">⌕</span><input id="copySearch" type="search" name="search" value="{{ request('search') }}" maxlength="120" placeholder="Cari kode, barcode, atau judul…" spellcheck="false"><button class="search-field__clear" type="button" data-search-clear aria-label="Hapus pencarian" hidden><span data-solar-icon="solar:close-circle-linear" aria-hidden="true">×</span></button></div><div class="filter-bar__controls"><button class="btn btn--secondary" type="submit">Cari</button>@if(request()->filled('search'))<a class="filter-reset" href="{{ route('book-copies.index') }}">Reset</a>@endif</div></form>
<div class="table-card"><div class="table-wrapper"><table class="data-table"><thead><tr><th scope="col">Kode / buku</th><th scope="col">Barcode</th><th scope="col">Kondisi</th><th scope="col">Status</th><th scope="col">Ubah status</th></tr></thead><tbody>@forelse($copies as $copy)<tr><td><strong>{{ $copy->inventory_code }}</strong><span class="table-subtitle">{{ $copy->book->title }}</span></td><td>{{ $copy->barcode ?: '—' }}</td><td>{{ ['good'=>'Baik','minor_damage'=>'Rusak ringan','damaged'=>'Rusak'][$copy->condition] }}</td><td><span class="badge badge--neutral">{{ $statusLabels[$copy->status] ?? $copy->status }}</span></td><td><form method="POST" action="{{ route('book-copies.update',$copy) }}" class="payment-form">@csrf @method('PATCH')<select name="status" aria-label="Status {{ $copy->inventory_code }}">@foreach($statusLabels as $value=>$label)<option value="{{ $value }}" @selected($copy->status===$value)>{{ $label }}</option>@endforeach</select><select name="condition" aria-label="Kondisi {{ $copy->inventory_code }}">@foreach(['good'=>'Baik','minor_damage'=>'Rusak ringan','damaged'=>'Rusak'] as $value=>$label)<option value="{{ $value }}" @selected($copy->condition===$value)>{{ $label }}</option>@endforeach</select><button type="submit" class="btn btn--secondary">Ubah</button></form></td></tr>@empty<tr><td colspan="5"><div class="empty-state empty-state--small"><h2>{{ request()->filled('search') ? 'Eksemplar tidak ditemukan' : 'Belum ada eksemplar' }}</h2><p>{{ request()->filled('search') ? 'Coba gunakan kode, barcode, atau judul lain.' : 'Tambahkan salinan fisik untuk mulai memakai kode inventaris dan barcode.' }}</p></div></td></tr>@endforelse</tbody></table></div></div></section>
@endsection
